/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectfinal;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author OSCAR
 */
public class EditarMapa extends javax.swing.JFrame {

    IO ES = new IO();
    HashMap<String, ArrayList<Grafo.Nodo>> nodoLista;
    ClaseUsuaria ms;

    /**
     * Creates new form EditarMapa
     */
    public EditarMapa() {
        Aereopuertos = new DefaultListModel();
        conexiones = new DefaultListModel();
        initComponents();
        LeerNodos();
        ms = new ClaseUsuaria(this.mapaPanel, this.mapa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        minPanel = new javax.swing.JPanel();
        minButton = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        mapaPanel = new javax.swing.JPanel();
        mapa = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameAereopuerto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        conexionesLista = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAereopuertos = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(193, 249, 250));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minPanel.setBackground(new java.awt.Color(221, 221, 221));

        minButton.setBackground(new java.awt.Color(153, 0, 153));
        minButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        minButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minButton.setText("—");
        minButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout minPanelLayout = new javax.swing.GroupLayout(minPanel);
        minPanel.setLayout(minPanelLayout);
        minPanelLayout.setHorizontalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        minPanelLayout.setVerticalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        header.add(minPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 30, 30));

        exitPanel.setBackground(new java.awt.Color(217, 217, 217));

        exitButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Header.png"))); // NOI18N
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 30));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO_4.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        mapaPanel.setLayout(null);

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mapa_5.png"))); // NOI18N
        mapaPanel.add(mapa);
        mapa.setBounds(0, 0, 840, 420);

        jPanel1.add(mapaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 840, 420));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backIcon_2.png"))); // NOI18N
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 31, -1, -1));

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del Aereopuerto:");
        panelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        nameAereopuerto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        nameAereopuerto.setForeground(new java.awt.Color(204, 204, 204));
        nameAereopuerto.setText("Ingrese Nombre del Aereopuerto");
        nameAereopuerto.setBorder(null);
        nameAereopuerto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameAereopuertoMouseClicked(evt);
            }
        });
        panelDatos.add(nameAereopuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 242, -1));
        panelDatos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, -1));

        conexionesLista.setBackground(new java.awt.Color(240, 240, 240));
        conexionesLista.setModel(conexiones);
        jScrollPane1.setViewportView(conexionesLista);

        panelDatos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 100));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Conexiones:");
        panelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Guardar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelDatos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, 30));

        listaAereopuertos.setBackground(new java.awt.Color(240, 240, 240));
        listaAereopuertos.setModel(Aereopuertos);
        listaAereopuertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAereopuertosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaAereopuertos);

        panelDatos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 100));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        btnAgregar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelDatos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Aereopuertos Disponibles:");
        panelDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 420));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Ubica el puntero en su posicion:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/New FONDO.png"))); // NOI18N
        BackGround.setText(" ");
        BackGround.setFocusable(false);
        jPanel1.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 570));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LeerNodos() {
        Grafo g;
        g = ES.leerDeArchivo();
        nodoLista = g.getGrafo();
        Aereopuertos.removeAllElements();
        for (String key : nodoLista.keySet()) {
            Aereopuertos.addElement(key);
        }

    }
    private void minButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minButtonMouseClicked

    private void minButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseEntered
        // TODO add your handling code here:
        minPanel.setBackground(new Color(128, 241, 244));
    }//GEN-LAST:event_minButtonMouseEntered

    private void minButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseExited
        // TODO add your handling code here:
        minPanel.setBackground(new Color(193, 249, 250));
    }//GEN-LAST:event_minButtonMouseExited

    private void minButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMousePressed
        // TODO add your handling code here:
        minPanel.setBackground(new Color(0, 112, 168));
    }//GEN-LAST:event_minButtonMousePressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        // TODO add your handling code here:
        exitPanel.setBackground(Color.red);
        exitButton.setForeground(Color.white);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        // TODO add your handling code here:
        exitPanel.setBackground(new Color(193, 249, 250));
        exitButton.setForeground(Color.black);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        // TODO add your handling code here:
        exitPanel.setBackground(new Color(153, 0, 0));
    }//GEN-LAST:event_exitButtonMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        int xMouse = 0;
        int yMouse = 0;
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        int xMouse = evt.getX();
        int yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
        Mapa map = new Mapa();
        this.setVisible(false);
        map.setVisible(true);
    }//GEN-LAST:event_MenuMouseClicked

    private void listaAereopuertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaAereopuertosMouseClicked
        // TODO add your handling code here:
        listaAereopuertos.getSelectedValue();
        Grafo g = ES.leerDeArchivo();
        nodoLista = g.getGrafo();
        Grafo.Nodo Encontrado;
        conexiones.removeAllElements();
        ArrayList<Grafo.Nodo> grafito = nodoLista.get(listaAereopuertos.getSelectedValue());
        conexionesLista.setEnabled(true);
        for (Grafo.Nodo nodo : grafito) {
            conexiones.addElement(nodo.getVertice());
        }
        if (conexiones.isEmpty()) {
            conexiones.addElement("No hay conexiones a otros aereopuertos");
            conexionesLista.setEnabled(false);
        }
    }//GEN-LAST:event_listaAereopuertosMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        Grafo g = ES.leerDeArchivo();
        g.agregarVertice(nameAereopuerto.getText());
        ES.imprimirEnArchivo(g);
        ms.Nuevo_Objeto();
        LeerNodos();
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void nameAereopuertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameAereopuertoMouseClicked
        // TODO add your handling code here:
        if (nameAereopuerto.getText().equals("Ingrese Nombre del Aereopuerto")) {
            nameAereopuerto.setForeground(Color.BLACK);
            nameAereopuerto.setText("");
            nameAereopuerto.setFocusable(true);
            nameAereopuerto.requestFocus();
        }
    }//GEN-LAST:event_nameAereopuertoMouseClicked

    private DefaultListModel Aereopuertos, conexiones;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Menu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JList<String> conexionesLista;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listaAereopuertos;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mapa;
    private javax.swing.JPanel mapaPanel;
    private javax.swing.JLabel minButton;
    private javax.swing.JPanel minPanel;
    private javax.swing.JTextField nameAereopuerto;
    private javax.swing.JPanel panelDatos;
    // End of variables declaration//GEN-END:variables
}
