/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectfinal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author OSCAR
 */
public class Mapa extends javax.swing.JFrame {

    ClaseUsuaria ms;
    int xMouse, yMouse;
    InicioSesion inicioS;
    Grafo g = new Grafo(true);
    IO SE = new IO();
    File x;
//     pinMap=new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Mapa() {
        Rutas = new DefaultListModel();
        x = new File("Grafo.obj");
        if (!x.exists()) {
            Grafo();
            System.out.println("Grafo cargado");
        }
        g = SE.leerDeArchivo();
        pinMap = new ArrayList<>();
        initComponents();
        ms = new ClaseUsuaria(this.mapaPanel, this.mapa);
//        ms.repintar();
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        x = new File("Pin.obj");
        if (x.exists()) {
            ms.pintarFijos();
//            ms.repintar();
        }

    }

    public final void Grafo() {
        g.agregarVertice("1");
        g.agregarVertice("2");
        g.agregarVertice("3");
        g.agregarVertice("4");
        g.agregarVertice("5");
        g.agregarArista("1", "3", 1);
//        pinMap.add(new JLabel());
        g.agregarArista("1", "2", 9);
        g.agregarArista("1", "4", 2);
        g.agregarArista("3", "2", 4);
        g.agregarArista("2", "3", 3);
        g.agregarArista("2", "1", 7);
        g.agregarArista("2", "5", 5);
        SE.imprimirEnArchivo(g);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        busquedaPanel = new javax.swing.JPanel();
        origen = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        cajaOrigen = new javax.swing.JTextField();
        cajaDestino = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        buscarPanel = new javax.swing.JPanel();
        buscarButton = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        minPanel = new javax.swing.JPanel();
        minButton = new javax.swing.JLabel();
        exitPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        mapaPanel = new javax.swing.JPanel();
        mapa = new javax.swing.JLabel();
        rutasPanel = new javax.swing.JPanel();
        rutDisp = new javax.swing.JLabel();
        listaRutas = new javax.swing.JScrollPane();
        listRutas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        botonReservar = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busquedaPanel.setBackground(new java.awt.Color(255, 255, 255));
        busquedaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        origen.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        origen.setText("Origen:");
        busquedaPanel.add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, -1, -1));

        destino.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        destino.setText("Destino: ");
        busquedaPanel.add(destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cajaOrigen.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cajaOrigen.setForeground(new java.awt.Color(153, 153, 153));
        cajaOrigen.setText("Ingrese Origen");
        cajaOrigen.setBorder(null);
        cajaOrigen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaOrigen.setFocusable(false);
        cajaOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaOrigenMousePressed(evt);
            }
        });
        cajaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaOrigenActionPerformed(evt);
            }
        });
        busquedaPanel.add(cajaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 21));

        cajaDestino.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cajaDestino.setForeground(new java.awt.Color(153, 153, 153));
        cajaDestino.setText("Ingrese Destino");
        cajaDestino.setBorder(null);
        cajaDestino.setFocusable(false);
        cajaDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaDestinoMousePressed(evt);
            }
        });
        busquedaPanel.add(cajaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 161, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        busquedaPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, 7));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        busquedaPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 160, 10));

        buscarPanel.setBackground(new java.awt.Color(107, 204, 221));
        buscarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        buscarButton.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        buscarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarButton.setText("Buscar");
        buscarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buscarPanelLayout = new javax.swing.GroupLayout(buscarPanel);
        buscarPanel.setLayout(buscarPanelLayout);
        buscarPanelLayout.setHorizontalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        buscarPanelLayout.setVerticalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        busquedaPanel.add(buscarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, 30));

        error.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        busquedaPanel.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 40, 190, -1));

        jPanel1.add(busquedaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 260, 140));

        header.setBackground(new java.awt.Color(193, 249, 250));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minPanel.setBackground(new java.awt.Color(193, 249, 250));

        minButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        minButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minButton.setText("—");
        minButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout minPanelLayout = new javax.swing.GroupLayout(minPanel);
        minPanel.setLayout(minPanelLayout);
        minPanelLayout.setHorizontalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        minPanelLayout.setVerticalGroup(
            minPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        header.add(minPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 30, 30));

        exitPanel.setBackground(new java.awt.Color(193, 249, 250));

        exitButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitPanelLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 30, 30));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO_4.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        mapaPanel.setLayout(null);

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mapa_5.png"))); // NOI18N
        mapaPanel.add(mapa);
        mapa.setBounds(0, 0, 840, 420);

        jPanel1.add(mapaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 840, 420));

        rutasPanel.setBackground(new java.awt.Color(255, 255, 255));
        rutasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rutDisp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rutDisp.setText("Rutas Disponibles:");
        rutasPanel.add(rutDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        listRutas.setBackground(new java.awt.Color(204, 204, 204));
        listRutas.setModel(Rutas);
        listaRutas.setViewportView(listRutas);

        rutasPanel.add(listaRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 240, 153));

        jPanel2.setBackground(new java.awt.Color(107, 204, 221));

        botonReservar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        botonReservar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonReservar.setText("Reservar");
        botonReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonReservarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReservar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonReservar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        rutasPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 205, 90, 30));

        jPanel1.add(rutasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 260, 260));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuIcon.png"))); // NOI18N
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Blueclimb.png"))); // NOI18N
        BackGround.setFocusable(false);
        jPanel1.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 570));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarPin(JPanel panel) {

    }

    private void cajaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaOrigenActionPerformed

// EVENTOS HEADER //////////////////////////////////////////////////////////////    
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

//EVENTOS EXIT ///////////////////////////////////////////////////////////////////////    
    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:        
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        // TODO add your handling code here:
        exitPanel.setBackground(Color.red);
        exitButton.setForeground(Color.white);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        // TODO add your handling code here:
        exitPanel.setBackground(new Color(193, 249, 250));
        exitButton.setForeground(Color.black);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        // TODO add your handling code here:
        exitPanel.setBackground(new Color(153, 0, 0));
    }//GEN-LAST:event_exitButtonMousePressed

    private void minButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minButtonMouseClicked

    private void minButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseEntered
        // TODO add your handling code here:
        minPanel.setBackground(new Color(128, 241, 244));
    }//GEN-LAST:event_minButtonMouseEntered

    private void minButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseExited
        // TODO add your handling code here:
        minPanel.setBackground(new Color(193, 249, 250));
    }//GEN-LAST:event_minButtonMouseExited

    private void minButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMousePressed
        // TODO add your handling code here:
        minPanel.setBackground(new Color(0, 112, 168));
    }//GEN-LAST:event_minButtonMousePressed

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
        inicioS = new InicioSesion();
        this.setVisible(false);
        inicioS.setVisible(true);

    }//GEN-LAST:event_MenuMouseClicked

    private void cajaOrigenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaOrigenMousePressed
        // TODO add your handling code here:
        if (cajaOrigen.getText().equals("Ingrese Origen")) {
            cajaOrigen.setForeground(Color.BLACK);
            cajaOrigen.setText("");
            cajaOrigen.setFocusable(true);
            cajaOrigen.requestFocus();
        }
        if (cajaDestino.getText().isEmpty()) {
            cajaDestino.setForeground(Color.GRAY);
            cajaDestino.setText("Ingrese Destino");
        }
    }//GEN-LAST:event_cajaOrigenMousePressed

    private void cajaDestinoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaDestinoMousePressed
        // TODO add your handling code here:
        if (cajaDestino.getText().equals("Ingrese Destino")) {
            cajaDestino.setForeground(Color.BLACK);
            cajaDestino.setText("");
            cajaDestino.setFocusable(true);
            cajaDestino.requestFocus();
        }
        if (cajaOrigen.getText().isEmpty()) {
            cajaOrigen.setForeground(Color.GRAY);
            cajaOrigen.setText("Ingrese Origen");
        }
    }//GEN-LAST:event_cajaDestinoMousePressed

    private void buscarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonMousePressed
        // TODO add your handling code here:

        try {
            ArrayList<ArrayList<String>> resp = g.caminos(cajaOrigen.getText(), cajaDestino.getText());
            error.setText("");
            System.out.println("Rutas:");
            String cadena = "";
            Rutas.removeAllElements();
            for (int i = 0; i < resp.size(); i++) {
                cadena = "Ruta " + (i + 1) + ": ";
                for (int j = 0; j < resp.get(i).size(); j++) {
                    cadena += resp.get(i).get(j) + ", ";
                }
                cadena = cadena.substring(0, cadena.length() - 2) + ". ";
                System.out.println(cadena);
                Rutas.add(i, cadena);
            }
//            for (ArrayList<String> arrayList : resp) {
//                for (String string : arrayList) {
//
//                }
//            }
            if (cadena.isEmpty()) {
                System.out.println("No se encontraron Rutas");
                Rutas.addElement("No hay rutas disponibles");
            }
        } catch (NullPointerException e) {
//            JOptionPane.showMessageDialog(rootPane, "No existe el Origen","Error",JOptionPane.ERROR_MESSAGE);
            error.setText("No existe el origen, ingrese uno valido");
        }

//        ms.Nuevo_Objeto();
    }//GEN-LAST:event_buscarButtonMousePressed

    private void botonReservarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReservarMousePressed
        // TODO add your handling code here:
//        PideDatos pide = new PideDatos();
//        pide.setLocationRelativeTo(null);
//        this.setVisible(false);
//        pide.setVisible(true);

        ArrayList<Lista> copia = SE.leerDeArchivoPasajeros();
        try {
            boolean u = false;
            for (Lista list : copia) {
                System.out.println(list.getIdentificador());
                System.out.println(listRutas.getSelectedValue());
                System.out.println(list.getIdentificador().equals(listRutas.getSelectedValue()));
                if (list.getIdentificador().equals(listRutas.getSelectedValue())) {
                    PideDatos pide = new PideDatos(list);
                    pide.setLocationRelativeTo(null);
                    this.setVisible(false);
                    pide.setVisible(true);
                    u = true;
                    break;
                }

            }
            if (!u) {
                PideDatos pide = new PideDatos(new Lista(listRutas.getSelectedValue()));
                pide.setLocationRelativeTo(null);
                this.setVisible(false);
                pide.setVisible(true);
            }

        } catch (Exception e) {
            System.out.println("CREO QUE YA FUNCIONO!!!");
            PideDatos pide = new PideDatos(new Lista(listRutas.getSelectedValue()));
            pide.setLocationRelativeTo(null);
            this.setVisible(false);
            pide.setVisible(true);
        }

    }//GEN-LAST:event_botonReservarMousePressed
/////////////////////////////////////////////////////////////////////////////////

    private ArrayList<javax.swing.JLabel> pinMap;
    private DefaultListModel Rutas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Menu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel botonReservar;
    private javax.swing.JLabel buscarButton;
    private javax.swing.JPanel buscarPanel;
    private javax.swing.JPanel busquedaPanel;
    private javax.swing.JTextField cajaDestino;
    private javax.swing.JTextField cajaOrigen;
    private javax.swing.JLabel destino;
    private javax.swing.JLabel error;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> listRutas;
    private javax.swing.JScrollPane listaRutas;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mapa;
    private javax.swing.JPanel mapaPanel;
    private javax.swing.JLabel minButton;
    private javax.swing.JPanel minPanel;
    private javax.swing.JLabel origen;
    private javax.swing.JLabel rutDisp;
    private javax.swing.JPanel rutasPanel;
    // End of variables declaration//GEN-END:variables

}
